spring.application.name=mhlmbackend

spring.datasource.url=jdbc:postgresql://localhost:5432/mhlmdb
spring.datasource.username=mhlmUser
spring.datasource.password=mhlmPW

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
